### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by lsj9383** [hujingshuang/imageEncryption#1]
So cool, but the language of picture in the readme.md is not english, I can't understand the meaning.

**Comment by hujingshuang** [comment]
English version will be released later, please wait.

**Comment by lsj9383** [comment]
Can you use image process to identify all the numbers in a sudoku photo?

**Comment by hujingshuang** [comment]
- Maybe can try.

**Comment by hujingshuang** [comment]
- Besides, I'm going to run ten kilometers, will you go?

**Comment by lsj9383** [comment]
why not sent the message by qq?
